### ISSUE TITLE
API Key "hard-coded"

### ISSUE THREAD

**Issue by kreig303** [PedroBern/react-native-art-museums-app#3]
**Problem**
API key has to be hard-coded.

**Solution**
Turn API key into external variable.

**Steps**
1. Add `dotenv` support. Can define `.env` file with `API_KEY=XXX` in file contents.
2. Ensure `.env` is `.gitignore`d. :)

**Comment by PedroBern** [comment]
Yes I know! Thanks for the steps... Actually this was just a fun project, so I was not worried about it, but I will be looking into it when I have the time. Please if you fix, open a PR. Then I just add the API key to my env.

**Comment by kreig303** [comment]
@PedroBern... changes have been made and ci has passed.

Review and merge at your leisure!

**Comment by PedroBern** [comment]
#4 merged, thanks!
