### ISSUE TITLE
add items to devDependencies

### ISSUE THREAD

**Issue by kreig303** [PedroBern/react-native-art-museums-app#5]
Add:
- `codecov`
- `expo-cli`

to `devDependencies` in `package.json`.

This solves any problems with requiring these at a global level and is the recommended method.

Sister issue to #3... resolves some Travis CI issues.

**Comment by kreig303** [comment]
@PedroBern... changes have been made and ci has passed.

Review and merge at your leisure!

**Comment by PedroBern** [comment]
#4 merged, thanks!
